# See https://github.com/open-telemetry/opentelemetry-configuration for details on schema and examples

file_format: "1.0-rc.2"

resource:
  attributes:
    - name: service.name
      value: spring-boot-declarative-config-example

propagator:
  composite:
    - tracecontext:
    - baggage:

tracer_provider:
  processors:
    - batch:
        exporter:
          console:
  # Configure sampling to exclude health check endpoints
  sampler:
    rule_based_routing:
      fallback_sampler:
        always_on:
      # Filter to spans of this span_kind. Must be one of: SERVER, CLIENT, INTERNAL, CONSUMER, PRODUCER.
      span_kind: SERVER   # only apply to server spans
      # List of rules describing spans to drop. Spans are dropped if they match one of the rules.
      rules:
        # The action to take when the rule is matches. Must be of: DROP, RECORD_AND_SAMPLE.
        - action: DROP
          # The span attribute to match against.
          attribute: url.path
          # The pattern to compare the span attribute to.
          pattern: /actuator.*

meter_provider:
  readers:
    - periodic:
        exporter:
          console: